### ISSUE TITLE
Uncaught TypeError: Cannot read property 'results' of undefined

### ISSUE THREAD

**Issue by Kalizo** [monkeecreate/jquery.simpleWeather#207] opened 2016-02-08 08:16 UTC
I have this error for a few days on my website. When I click on Weather, it no longer works.

> Uncaught TypeError: Cannot read property 'results' of undefined

[http://www.detours-in-france.com/products/biking/canal-du-midi/canal-du-midi-self-guided-biking-tour-toulouse-to-sete](http://www.detours-in-france.com/products/biking/canal-du-midi/canal-du-midi-self-guided-biking-tour-toulouse-to-sete)

In addition, the CodePen site, I see exactly the same mistake!

[http://codepen.io/fleeting/pen/xklfq](http://codepen.io/fleeting/pen/xklfq)

Is the Yahoo API is down ? Would anyone have a solution?

**Comment by lowki** [comment] 2016-02-08 09:04
It seems to be related to Yahoo's API, here the xhr request error message
`   {"error":{"lang":"en-US","diagnostics":null,"description":"Tenant 'query_yahooapis_com' access to 'Resource [tenantName=query_yahooapis_com, type=TABLE, name=geo.placefinder, locatorType=FILE, url=/home/y/share/manhattan/application/tenantBundles/yql_query_yahooapis_com_manhattan_v2/YQL-INF/restdefs/geo.placefinder.xml, useUrl=false]' is denied."}}`

**Comment by fleeting** [comment] 2016-02-09 14:23
The demos are working for me. Yahoo did recently change their API and removed an end point I was using (`geo.placefinder`). This has been fixed in `v3.1.0` released a little over a week ago. You will need to update.

**Comment by chrishiam** [comment] 2016-02-11 13:38
Just wanted to say that this still seems to be an issue. None of the demos work for me.

**Comment by Kalizo** [comment] 2016-02-11 14:09
I updated jquery.simpleweather.js to 3.1.0 and now it works! But I'm agree with @chrishiam : [this demo](http://codepen.io/fleeting/pen/xklfq) doesn't work for me, and it is on plugin's homepage...

**Comment by fleeting** [comment] 2016-02-11 14:14
I'm not able to see an issue with that demo. It could have been Yahoo's API having issues again but the demo is returning weather data for me at the moment. What browser, version, and OS are you guys using?

**Comment by Kalizo** [comment] 2016-02-11 14:18
Windows 8.1 - Google Chrome 48.0.2564.109 m
![Screenshot](https://cloud.githubusercontent.com/assets/6975506/12978652/8fed4fee-d0d2-11e5-8d25-1650894cb0f8.png)

**Comment by fleeting** [comment] 2016-02-11 14:25
I just spun up a Windows 8.1 VM with Chrome 48 and the demo is currently working on it for me. I also had a few other people test on other devices without a problem so honestly not really sure the issue as I can't duplicate it.

**Comment by Kalizo** [comment] 2016-02-11 14:36
Hum OK : I testing it on private nav (Ctrl+Shift+N) without Chrome extensions and the demo works... Maybe one of my Chrome extensions broke the plugin ! AdBlock ?

**Comment by fleeting** [comment] 2016-02-11 16:00
Hmm, I would be interested in finding out if it was an extension causing the issue. If possible, could you disable your extensions and turn them on one at a time until the demo breaks? It might also be that the demo was heavily cached for you from when it was broken before `v3.1.0`. Private browsing uses it's own cache.

**Comment by chrishiam** [comment] 2016-02-11 16:03
I can rule out the caching option, today is the first time I've used this plugin. I'm not sure what happened but the demo is working for me now, nothing changed from the last time I viewed it. Did you change something on your end?

**Comment by biapar** [comment] 2016-02-19 08:57
The problem is solved with new version.

**Comment by Kalizo** [comment] 2016-02-19 09:12
I confirm ! The demo works even with normal Chrome extensions.

**Closed** 2016-02-22 14:11 UTC
