### ISSUE TITLE
Simple Weather seems to be down

### ISSUE THREAD

**Issue by whatmatterson** [monkeecreate/jquery.simpleWeather#177] opened 2016-01-20 06:34 UTC
Hi, I just started using Simple Weather on a site I'm developing, and it was working great for a day, then I noticed it wasn't showing up today. I checked your site and the codepen demo, and those don't seem to be showing up.

Thanks!

**Comment by ravisheee** [comment] 2016-01-20 08:28
Hi,
Even i am using simply weather plugin and it seems to be down. The issue is in the line data.query.results.channel in simpleweather.js file and the error message thrown by browser is " Unable to get property 'channel' of undefined or null reference".

Because of the above issue, the demo site is even down.

Thanks

**Comment by BonnieDoug** [comment] 2016-01-20 09:50
+1

**Comment by haranbatti** [comment] 2016-01-20 10:03
Hi, I am also having issue with simple weather , I'm  getting error "Cannot read property 'channel' of null", Don't know why? :(

**Comment by Khano** [comment] 2016-01-20 10:31
There's a solution. from @ctrlaltdylan

https://github.com/ctrlaltdylan/jquery.simpleWeather/commit/be92402ff36f7fdf0b669530a9e38776be963f4e

**Comment by joaoferreira** [comment] 2016-01-20 11:47
I was having the same issue and solution from @ctrlaltdylan worked for me.
My suggestion to keep the original functionality is to remove the ``` and gflags="R" limit 1"  ``` and also replace the ``` geo.placefinder ``` by ``` geo.places(1) ```
This way the api will just return one object

**Comment by BonnieDoug** [comment] 2016-01-20 12:30
With @joaoferreira 's suggestion I now get

     Uncaught TypeError: Cannot read property 'channel' of null

**Comment by j0ssGZ** [comment] 2016-01-20 13:03
+1 Thanks @Khano but this solution does not work

**Comment by oasif** [comment] 2016-01-20 14:42
try 
weatherUrl += 'select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="'+options.location+'") and u="'+options.unit+'"';

**Comment by joaoferreira** [comment] 2016-01-20 14:59
@BonnieDoug this is the code that I changed in the original script to fix the issue. Starting on line 24.

```
if(options.location !== '') {
        weatherUrl += 'select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="'+options.location+'") and u="'+options.unit+'"';
      } else if(options.woeid !== '') {
        weatherUrl += 'select * from weather.forecast where woeid='+options.woeid+' and u="'+options.unit+'"';
      } else {
        options.error({message: "Could not retrieve weather due to an invalid location."});
        return false;
      }
```

To test this you can use the weatherUrl variable in the browser and check what is returned.

**Comment by iantbarker** [comment] 2016-01-20 16:07
Anyone else getting today's high and low for the forecasted high and low? 

I'm using weather.forecast[i].high and weather.forecast[i].low where but it seems to return today's high and low. The forecast for code and text work fine.

**Comment by balazsegyed** [comment] 2016-01-20 16:11
@joaoferreira I tested your soulution, but it doesn't solve the problem.

The same situation than the first try.
Uncaught TypeError: Cannot read property 'channel' of null

So I write the weatherURL with console.log and downloaded the txt file.
```javascript
/**/yql_invalid_callback({"error":{"lang":"en-US","diagnostics":null,"description":"Invalid JSON callback parameter yql_invalid_callback"}});
```

Than I deleted the &callback=? from the line 24. Console.log again:
```javascript
,"http-status-code":"503","http-status-message":"Service Unavailable",
```
[link for the forecast](https://query.yahooapis.com/v1/public/yql?format=json&rnd=20160317&diagnostics=true&q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.placefinder%20where%20text=%2247.51758660000001,19.750028%22%20and%20gflags=%22R%22%20limit%201)%20and%20u=%22c%22)

**Comment by wlerner** [comment] 2016-01-20 16:56
+1

I am experiencing the same issue and the solution offered here https://github.com/ctrlaltdylan/jquery.simpleWeather/commit/be92402ff36f7fdf0b669530a9e38776be963f4e did not work.  I believe this issue should still be considered a problem.

**Comment by joaoferreira** [comment] 2016-01-20 18:07
@balazsegyed you are using lat/long and according with @ascott23 that's what causing the issue and there is no workaround for your scenario because Yahoo service it not working properly.
Consider to change the lat/long to an address and it might work, you can find more information here:
https://github.com/monkeecreate/jquery.simpleWeather/issues/174

**Comment by balazsegyed** [comment] 2016-01-20 20:57
Thanks, it's works for me.

**Comment by Emmaluc** [comment] 2016-01-21 09:15
Thx it works for me too.@joaoferreira

**Comment by fleeting** [comment] 2016-01-21 13:28
Closing this in favor of #174.

**Closed by fleeting** 2016-01-21 13:28 UTC

**Comment by TheSniper102** [comment] 2016-02-22 16:19
i fixed by link new library
https://cdnjs.cloudflare.com/ajax/libs/jquery.simpleWeather/3.1.0/jquery.simpleWeather.min.js
